#+title: Religion
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

#+OPTIONS: num:nil
#+OPTIONS: ^:t

#+BEGIN_EXPORT html
<nav>
    <a href="./index.html">Home</a> |
    <a href="">Blogs</a> |
    <a href="https://github.com/ethanxxxl">Github</a> |
    <a href="./religion.html">Religion</a> |
    <a href="">Portfolio</a>
</nav>
#+END_EXPORT

* Procrastination
I often find myself procrastinating things. These things range from insignificant to crucial, time-critical tasks that must be completed or I will face severe consequences. I never understood why I procrastinated so much. After everything was said and done, I typically tell myself that it was dumb to push that thing off so long, and that if I had only started earlier, I would have been able to do a better job. As a college student, procrastination is seen as a given: it's how most students get motivation to complete their assignments. I have often touted procrastination as the superior way of operating in the college environment. I thought I was more efficient with my time, completing assignments in a fraction of the time my peers did, if not only because I didn't allocate enough time in the first place.

I am now finishing my time in school. I have had some time to reflect on my habits, and how those actions have affected me, physically, emotionally, and spiritually. I have come to view procrastination of a much more serious sin pattern. The root of procrastination is selfishness.  What do I do when I procrastinate? I engage in various forms of self-indulgence. I seek ways to fulfill and gratify myself which are quicker and easier than the task at hand. This is a problem because God created man to work, to be productive:
#+BEGIN_QUOTE
The LORD God took the man and put him in the garden of Eden to work it and keep it.\\
Genesis 2:15
#+END_QUOTE
When we participate in God's plan, his will, we glorify him. God wants us to work, labor, and produce things for the purpose of blessing the people around us. How can I be blessing others when  I am focused on my own pleasure? When I procrastinate, my actions are innately self serving, and by definition I am unable to fulfill my God-given charge to bless others through my work. I am no longer serving God! Instead I serve and glorify myself.

This selfishness is very infectious. Once I let my guard down, indulging in self gratification for even a moment, that sin takes hold of me, which leads to more sin. Once I stray from Gods grace, I am completely ineffective as an ambassador for Christ. I don't seek ways to serve others, I don't spend time in prayer, or even read my Bible. Only once I "cry out from the pit", realizing that God is my only method of escape can I be restored.
#+BEGIN_QUOTE
You have wrapped yourself with a cloud\\
    so that no prayer can pass through.

I called on your name, O LORD,\\
    from the depths of the pit;\\
you heard my plea, 'Do not close\\
    your ear to my cry for help!'\\
You came near when I called on you;\\
    you said, 'Do not fear!'\\
Lamentations 3:44; 55-57
#+END_QUOTE
This passage in Lamentations perfectly describes how I feel in the midst of a season of selfishness. I feel that I am unable to talk to God or read my Bible. I struggle to do these things because I have not humbled myself before coming to God. I come to him, asking for his presence while I continue to glorify myself. How that must offend God! It is only once I repent of my sin, humble myself, and acknowledge God as the true source of my satisfaction and fulfillment that I can regain that close relationship with the Spirit.

#+BEGIN_QUOTE
The more they increased,\\
    the more they sinned against me;\\
    I will change their glory into shame.\\
Hosea 4:7
#+END_QUOTE

#+BEGIN_QUOTE
Do not be slothful in zeal, be fervent in spirit, serve the Lord.\\
Romans 12:11
#+END_QUOTE

#+BEGIN_QUOTE
Contribute to the needs of the saints and seek to show hospitality.\\
Romans 12:13
#+END_QUOTE

Ethan Smith\\
Mon Apr  3 04:11:15 2023


* Faith Tested by Fire
This is a study on the first few verses of 1 Peter.

#+begin_quote
‍^{1}Peter, an apostle of Jesus Christ, To those who are elect exiles of the
Dispersion in Pontus, Galatia, Cappadocia, Asia, and Bithynia,‍ ‍^{2}according to the
foreknowledge of God the Father, in the santification of the Spirit, for
obedience to Jesus Christ and for sprinkling with his blood:\\
  May grace and peace be multiplied to you
#+end_quote

We start out with a greeting. In the greeting we learn that:
- Peter is an apostle, and has identified himself with Jesus.
- He is writing to the displaced Christians in what is now Turkey.
- That God is sovereign over their salvation (v2).
- Their purpose is to be obedient to and sanctified by Christ.

This prelude sets the tone of the first chapter. Peter will got one to discuss
how and why we suffer as Christians. This was written to displaced peoples.
People who may have been dispursed because of their faith. They may be wondering
why God is allowing them to endure so much suffering. Peter casts light onto
this.

#+begin_quote
‍^{3}Blessed be the God and Father of our Lord Jesus Christ! According to his great
mercy, he has caused us to be born again to a living hope through the
resurrection of Christ from the dead, ‍^{4}to an inheritance that is imperishable,
undefiled, and unfading, kept in heaven for you, ‍^{5}who by God's power are being
guarded through faith for a salvation ready to be revealed in the last time.
#+end_quote

Because of Christs death, we can have hope through our trials and suffering.
This earth has been tainted by sin. Everything on this earth will pass away. It
will fade into the obscure annals of history, forgotten. We can have hope,
because we don't put our faith in the things of this world! Christ has promised
us a treasure untainted by sin, permanent, and everlasting. This treasure is
kept for us, by Christ, in heaven.

Christ wants to see us collect our treasure from him in heaven. This is why
Christ gave us the Spirit. God's power guards us agains the powers of this
world. /I will not leave you as orphans; I will come to you --John 14:18/. We
aren't left out to fend for ourselves. This was the whole point of the
crucifiction: That we could wholly rely on the power of God to save and protect
us from the sin of this world.

One may ask, as I'm sure the recipients of this letter did: If God's provision
for is so great, then why do we continue to suffer in this world? Why are we
constantly railed by temptation and sin? If God loves us, why doesn't he just
take away our suffering?

#+begin_quote
‍^{6}In this you rejoice, though now for a little while, if necessary, you have been
grieved by various trials, ‍^{7}so that the tested genuiness of your faith--more
precious than gold that perishes though it is tested by fire--may be found to
result in praise and glory and honor at the revelation of Jesus Christ.
#+end_quote

The reason we are allowed to endure suffering is because God loves us. He is so
concerned for the purity of our hearts, that he allows said purity to be tried
and tested for a little while. Peter equates faith that stands firm to gold.
Gold, once it has been refined and purified, is incredibly valuable. But the
gold will pass away in the end. It does not last forever. Faith, once it has
been purified, (that is, faith that will result in praise and glory and honor),
does not perish. It resides in the same domain as the treasure Christ is holding
for us in heaven. This faith is the most valuable thing that one can possess.

Sincere faith is like an investment from God. Once we have accepted his gift of
salvation, he starts the refining process. He desires to give us the most
valuable gift he can bestow on us. And like any investment, this gift grows more
valuable with time. As we endure suffering, parts of our character inconsistant
with God's will are burned away. Purification is a hard, lifelong process, but
it is necessary. God is not content for us to live with impurities. He allows us
to endure trials so that we may see where our faith is weak and impure. /Count
it all joy, my brothers, when you meet trials of various kinds, for you know
that the testing of your faith produces steadfastness. And let steadfastness
have its full effect, that you may be perfect and complete, lacking in nothing.
--James 1:2-4/

When we face trials, whether internal or external, either temptation of
hardship, we can have joy and hope. So long as we have repentance, that trial
will result in the purification of our hearts. If during the trial, we renege on
our end of our covenant with God (ie, we fall into sin), God is faithful. The
incongruities of our faith are made clear to us, and we can continue to pursue
purity in Christ. /For I am sure that neither death nor life, nor angels nor
rulers, nor things present nor things to come, nor powers, nor height nor depth,
nor anything else in all creation, will be able to separate us from the love of
God in Christ Jesus our Lord./

Ethan Smith\\
Sat Apr  8 16:15:09 2023
