#+title: Study of 1 Peter
#+include: "includes.org"

#+html: <div class="blog-content">
* Have Hope, You Are Sought Out
Continuing with 1 Peter, these are my notes from a brief study I did on a short
part of this book.

In these verses, Peter directs his audience to set their minds on the things of
heaven, rather than the things of earth. His audience consists of Christians who
are likely Gentiles, who worshiped pagan gods before their conversions. While he
instructs them to remember holy things, he doesn't leave them without
motivation. He draws their attention to the work done by Christ on the cross,
who in his suffering bore their shame so they wouldn't have to. While his
audience most certainly has a different background than we do, we can certainly
still find application in this passage today.

#+begin_quote
‍^{13}Therefore, preparing your minds for action, and being sober-minded, set
your hope fully on the grace that will be brought to you at the revelation of
Jesus Christ. ‍^{14}As obedient children, do not be conformed to the passions of
your former ignorance, ‍^{15}but as he who called you is holy, you also be holy
in all your conduct, ‍^{16}since it is written, "You shall be holy, for I am
holy."
#+end_quote

First off, there is a "Therefore." Peter is referring to the point he made
previously, regarding the prophets of the Old Testament. These prophets
prophesied things that they could not understand. They knew of God's promised
plan for redemption but had no comprehension of how or when God would execute
His plan. Yet, these gentiles who have lived lives so far removed from Judaism,
and thus from knowledge of the One True God, have the privileged of a deep
understanding of the gospel. An understanding deeper than that of even the
prophets.

This point, especially when you look at verse 12, strongly suggests that these
early Christians aren't simply fortunate. God actively sought them out. First,
he proclaims what he will do through the prophets. Then, he does what he said he
would do. Finally, he sends his Holy Spirit, who directs people to be a witness
to the nations, specifically the audience of Peters's letter! No matter how you
came to Christ, you can surely be thankful for the ways that God sought you out,
even before you were a thought in your parent's minds. Yes, you can trace back
God's pursuit of you back to the fall, where God laid out his plan of salvation
at the beginning of all human depravity.

"Therefore," our minds should be ready for action! What does this preparation
look like? What action will we take? The answer to the first question lies in
the next phrase: being sober-minded, with your hope set on God's Grace (brought
at the revelation of Christ). What does it mean to be sober-minded? Well, the
opposite of sober is drunkenness. When drunk, a person makes poor decisions,
often to their detriment. Peter is calling us to weigh our decisions, be
judicious, and consider what the most beneficial course of action may be. We are
to do this in light of what is to come, which is grace revealed at the
revelation of Christ. How can you be more self-preserving than by taking care of
your soul, which lasts forever? This is why we hope in the grace which will be
fully dispensed at Christ's second coming.

But what about the action? What are we supposed to do? The rest of the passage
is pretty clear on this. We are to be obedient as children! and like children,
Peter says that we should imitate our Father. Just as he is Holy, so too must we
be holy. I have heard people make the argument that Christians are fake; the
only reason they do good is that they are afraid of going to hell. However, this
isn't the image of Christianity Peter had! Peter puts forth that we should be
Holy because our Father, who pursued and redeemed us, is Holy.

So rather than living in fear and shame because of our evil, we can confidently
pursue righteousness. We know that our Father loves us and has sought us out. We
shouldn't be afraid of hell, we should be eagerly hoping for the return of our
King!

#+begin_quote
And they shall be called The Holy People,\\
    The Redeemed of the LORD;\\
and you shall be called Sought Out,\\
    A City Not Forsaken.\\
--Isaiah 62:12
#+end_quote

Ethan Smith\\
Wed Apr 19 04:47:35 2023


* Faith Tested by Fire
This is a study of the first few verses of 1 Peter.

#+begin_quote
‍^{1}Peter, an apostle of Jesus Christ, To those who are elect exiles of the
Dispersion in Pontus, Galatia, Cappadocia, Asia, and Bithynia,‍ ‍^{2}according to
the foreknowledge of God the Father, in the sanctification of the Spirit, for
obedience to Jesus Christ and for sprinkling with his blood:\\
  May grace and peace be multiplied to you
#+end_quote

We start with a greeting. In the greeting, we learn that:
- Peter is an apostle and has identified himself with Jesus.
- He is writing to the displaced Christians in what is now Turkey.
- That God is sovereign over their salvation (v2).
- Their purpose is to be obedient to and sanctified by Christ.

This prelude sets the tone of the first chapter. Peter will go on to discuss how
and why we suffer as Christians. This was written to displaced peoples. People
who may have been dispersed because of their faith. They may be wondering why
God is allowing them to endure so much suffering. Peter casts light on this.

#+begin_quote
‍^{3}Blessed be the God and Father of our Lord Jesus Christ! According to his
great mercy, he has caused us to be born again to a living hope through the
resurrection of Christ from the dead, ‍^{4}to an inheritance that is
imperishable, undefiled, and unfading, kept in heaven for you, ‍^{5}who by God's
power are being guarded through faith for a salvation ready to be revealed in
the last time.
#+end_quote

Because of Christ's death, we can have hope through our trials and suffering.
This earth has been tainted by sin. Everything on this earth will pass away. It
will fade into the obscure annals of history, forgotten. We can have hope
because we don't put our faith in the things of this world! Christ has promised
us a treasure untainted by sin, permanent, and everlasting. This treasure is
kept for us, by Christ, in Heaven.

Christ wants to see us collect our treasure from him in heaven. This is why
Christ gave us the Spirit. God's power guards us against the powers of this
world. /I will not leave you as orphans; I will come to you --John 14:18/. We
aren't left out to fend for ourselves. This was the whole point of the
crucifixion: That we could wholly rely on the power of God to save and protect
us from the sin of this world.

One may ask, as I'm sure the recipients of this letter did: If God's provision
is so great, then why do we continue to suffer in this world? Why are we
constantly railed by temptation and sin? If God loves us, why doesn't he just
take away our suffering?

#+begin_quote
‍^{6}In this you rejoice, though now for a little while, if necessary, you have
been grieved by various trials, ‍^{7}so that the tested genuineness of your
faith--more precious than gold that perishes though it is tested by fire--may be
found to result in praise and glory and honor at the revelation of Jesus Christ.
#+end_quote


The reason we are allowed to endure suffering is that God loves us. He is so
concerned for the purity of our hearts, that he allows said purity to be tried
and tested for a little while. Peter equates faith that stands firm to gold.
Gold, once it has been refined and purified, is incredibly valuable. But the
gold will pass away in the end. It does not last forever. Faith, once it has
been purified, (that is, faith that will result in praise and glory and honor),
does not perish. It resides in the same domain as the treasure Christ is holding
for us in heaven. This faith is the most valuable thing that one can possess.

Sincere faith is like an investment from God. Once we have accepted His gift of
salvation, he starts the refining process. He desires to give us the most
valuable gift he can bestow on us. And like any investment, this gift grows more
valuable with time. As we endure suffering, parts of our character inconsistent
with God's will are burned away. Purification is a hard, lifelong process, but
it is necessary. God is not content for us to live with impurities. He allows us
to endure trials so that we may see where our faith is weak and impure. /Count
it all joy, my brothers, when you meet trials of various kinds, for you know
that the testing of your faith produces steadfastness. And let steadfastness
have its full effect, that you may be perfect and complete, lacking in nothing.
--James 1:2-4/

When we face trials, whether internal or external, either temptation or
hardship, we can have joy and hope. So long as we have repentance, that trial
will result in the purification of our hearts. If during the trial, we renege on
our covenant with God (ie, we fall into sin), God is faithful. The incongruities
of our faith are made clear to us, and we can continue to pursue purity in
Christ. /For I am sure that neither death nor life, nor angels nor rulers, nor
things present nor things to come, nor powers, nor height nor depth, nor
anything else in all creation, will be able to separate us from the love of God
in Christ Jesus our Lord./

Ethan Smith\\
Sat Apr  8 16:15:09 2023
#+html: </div>
