#+title: Ethan Smith

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: num:nil
#+OPTIONS: ^:t

#+include: "navbar.org"

# surround the main content with a div so that you can format it properly.
#+html: <div id="main-content">
* Overview

Hello and welcome to my website! I grew up in Western Pennsylvania with a
passion for technology. I started teaching myself programming when I was in
middle school, an endeavor which continues to this day. During High School, I
went to our local trade school and learned a little bit about electricity and
circuits. I love the intersection of hardware and software, so much so that I
decided to spend four years of my life at Penn State, studying Electrical
Egineering, with a minor in Computer Engineering. I am currently a Senior, and
am very excited to leave the education system (for a while at least). Going to
college also afforded me the opportunity to join the United States Air Force
through AFROTC. I am slated to commission in May 2023 (Lord willing) as a 2nd
Lt, as an Electrical Developmental Engineer (62EX). I am told that I will be
unecessary that I know /when/ I will be moving, I am told that at some
point, I will be moving to Wright Patterson AFB (Ohio) to work at NASIC
(National Air and Space Intelligence Center). I had the pleasure of staying at
WPAFB last summer for a month long "Advance Cyber Education" program, which was
very fun.

# surround the main content with a div so that you can format it properly.
#+html: </div>
